language: csharp
solution: TestApp.sln
mono:
 - latest
install: 
 - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh 
 - dnvm upgrade
 - dnu restore
script: 
 - dnu build ./TestApp/project.json 
 - dnu build ./TestApp.Tests/project.json 
 - dnx -p ./TestApp.Tests test
after_success:
- curl --data build=true -X POST https://registry.hub.docker.com/u/cgsainty/dotnet-ci-test/trigger/f57eb1cd-756c-4080-8906-f9c8a75caf7c/